### ISSUE TITLE
Overview of downloadable images

### ISSUE THREAD

**Issue by isabellpaulmann** [isabellpaulmann/capstone-project#1]
## Value proposition

**As a** user, 
**I want to** have an overview of the wallpapers that can be downloaded
**so that** i can choose one and save it

## Description

<img src=xxx.png width=320px>

## Acceptance criteria

- [ ] The page is scrollable
- [ ] Containers wrap 
- [ ] Download button is implemented
- [ ] App logo is on top, but not sticky
- [ ] every Image has a download button

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Setup Storybook for ImageContainer
- [ ] Implement ImageContainer with Download button
- [ ] Write specs for the ImageContainer
- [ ] Add ImageContainer to the App
- [ ] Sort containers at the page
