### ISSUE TITLE
add drawing function

### ISSUE THREAD

**Issue by isabellpaulmann** [isabellpaulmann/capstone-project#12]
## Value proposition

**As a** user, 
**I want to** draw on my favorite wallpaper
**so that** i can personalize my wallpaper

## Description

![Bildschirmfoto 2022-07-13 um 09 22 05](https://user-images.githubusercontent.com/104442412/178674913-384e455d-0700-41f1-9493-da08d3453acf.png)

## Acceptance criteria

- [ ] by clicking on the draw mode button the user can paint on the selected wallpaper
- [ ] the painting function is only available on the detail page
- [ ] by clicking on the delete button the user can erase the drawing from the wallpaper
- [ ] by clicking on the color change button the user can change the color of the pen

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Add Canvas-Draw
- [ ] Add buttons for edit the drawing

**Comment by ahohnsen** [comment]
Hey Isabell,

Just a few thoughts:

- I think your acceptance criteria can be formulated a bit more specific e.g.:

     - By clicking on the draw mode button the user can paint on the selected wallpaper
     - By clicking on the delete button the user can erase the drawing from the wallpaper 
     - By clicking on the color change button the user can change the color (from the drawing?)

I would also suggest that you have a look at your various buttons again. Maybe it would be good to add a text, choose another icon or adjust the styling that it is more clear which button does what (remember my comment about your download & save button).
