### ISSUE TITLE
Homepage with buttons

### ISSUE THREAD

**Issue by isabellpaulmann** [isabellpaulmann/capstone-project#2]
## Value proposition

**As a** user, 
**I want to** would like to have a homepage where i can can choose my preferred color style
**so that** so that I can see now images that suit me

## Acceptance criteria

- [ ] The page is scrollable
- [ ] Download button is implemented
- [ ] App logo is on top, but not sticky
- [ ] every Image has a download button
- [ ] Container Wrap

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Setup Storybook for ImageContainer
- [ ] Implement ImageContainer with Download button
- [ ] Write specs for the ImageContainer
- [ ] Add ImageContainer to the App
- [ ] Sort containers at the page

**Comment by PReichetanz** [comment]
Hello Isabell,
looks good!

I want to drop some questions / ideas:
- Please check the value proposition again regarding grammar / unnecessary words.
- Since your buttons redirect to the overview page, please add a scribble to show how it works.
- "App logo is placed" is not necessary as acceptance criteria because it's already in the scribble.
- Do you need routing here? or how are both pages connected?
- How does the user see which color theme he/she chose before? How can he changes his decision? Is there a "Back"-Button on page 1 and / or a "Change theme"-Button?

**Comment by smilenow24** [comment]
that looks great - ist der download-button Platzhalter oder hat dieser schon eine Funktion?

**Comment by Huimin66** [comment]
Add the HomeButton to page1 -- if HomeButton is clicked, jumps the page really back to home page?
