### ISSUE TITLE
Overview of single image

### ISSUE THREAD

**Issue by isabellpaulmann** [isabellpaulmann/capstone-project#3]
## Value proposition

**As a** user, 
**I want to** have a better view of my chosen picture
**so that** i can see if i made the right choice or want to choose a new one

## Acceptance criteria

- [ ] The page is scrollable
- [ ] Download button is implemented
- [ ] App logo is on top, but not sticky
- [ ] every Image has a download button
- [ ] Container Wrap

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Setup Storybook for ImageContainer
- [ ] Implement ImageContainer with Download button
- [ ] Write specs for the ImageContainer
- [ ] Add ImageContainer to the App
- [ ] Sort containers at the page

**Comment by ahohnsen** [comment]
Hey Sarina,

A few suggestions for you:

Description:
- You do not need to show the reserved space for a button you are going to implement later on.
- The buttons should be shown in your scribble as they are going to look later on e.g. with text or an icon on the button - and then there is no need for an additional description of the buttons
- In the acceptance criteria you do not need to mention that your screen shows a back/home button. It is better to write here what is going to happen on a click e.g.:

_By clicking on the back button the user is redirected to..._

- I am not quite sure what you mean by: _the right ImageContainer is implemented_
- If you are going to use Routing (React Router) you should add it to your task list
- I guess you will also need to create a new component for this "detail page"
