### ISSUE TITLE
Sticker page

### ISSUE THREAD

**Issue by isabellpaulmann** [isabellpaulmann/capstone-project#4]
## Value proposition

**As a** user, 
**I want to** add nice stickers to my chosen picture
**so that** i can personalize my wallpaper

## Description

![Bildschirmfoto 2022-06-23 um 11 24 51](https://user-images.githubusercontent.com/104442412/175265693-33c6e847-958b-4cdc-94f8-8194bdab2414.png)

## Acceptance criteria

- [ ] The page have a Back-Button and a homepage-button
- [ ] the right ImageContainer is implemented

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Setup Storybook for GoBackButton
- [ ] Setup Storybook for HomepageButton
- [ ] Implement GoBackButton
- [ ] Implement HomepageButton
- [ ] Write specs for the GoBackButton + HomepageButton
- [ ] Add ImageContainer
