### ISSUE TITLE
setting options for image

### ISSUE THREAD

**Issue by isabellpaulmann** [isabellpaulmann/capstone-project#9]

**Comment by isabellpaulmann** [comment]
## Value proposition

**As a** user, 
**I want to** as a user i want to change my selected wallpaper with filters
**so that** i can personalize my wallpaper

## Description

![Bildschirmfoto 2022-07-06 um 14 07 35](https://user-images.githubusercontent.com/104442412/177546467-00e0bd06-f2ad-473b-b386-fb4b368c177c.png)


## Acceptance criteria

- [ ] The page have 3 filter buttons 
- [ ] The Filters change Brightness, Contrast and Color

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add base styles
- [ ] Implement Buttons on the Overview Page
